// import type { Metadata } from "next";
// import { Roboto_Flex } from 'next/font/google';
// import "./globals.css";

// const roboto = Roboto_Flex({
//   subsets: ['latin'],
//   weight: ['100', '400', '700'],
//   variable: '--font-roboto',
// });


// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
//   icons: {
//     icon: "/favicon.ico",  // 👈 add this line
//   },
// };

// export default function RootLayout({
//   children,
// }: {
//   children: React.ReactNode;
// }) {
//   return (
//      <html lang="en" className={`${roboto.variable}`}>
//           <body className="font-sans antialiased">
//           {children}
//         </body>
//      </html>
//   );
// }


// // src/app/layout.tsx
// import type { Metadata } from "next";
// import { Roboto_Flex } from 'next/font/google';
// import "./globals.css";
// import GoogleTranslate from "../components/GoogleTranslate"; // ⬅ import the new component

// const roboto = Roboto_Flex({
//   subsets: ['latin'],
//   weight: ['100', '400', '700'],
//   variable: '--font-roboto',
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
//   icons: {
//     icon: "/favicon.ico",
//   },
// };

// export default function RootLayout({
//   children,
// }: {
//   children: React.ReactNode;
// }) {
//   return (
//     <html lang="en" className={roboto.variable}>
//       <body className="font-sans antialiased">
//         <GoogleTranslate /> 
//         {children}
//       </body>
//     </html>
//   );
// }



/* frontend/src/app/layout.tsx
   ───────────────────────────────────────────────────────────── */
/* frontend/src/app/layout.tsx */
import type { Metadata } from 'next';
import { Roboto_Flex } from 'next/font/google';
import './globals.css';

const roboto = Roboto_Flex({
  subsets: ['latin'],
  weight: ['100', '400', '700'],
  variable: '--font-roboto',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
  icons: { icon: '/favicon.ico' },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={roboto.variable}>
      <head>
        {/* This meta tag alone suppresses Chrome’s auto-translate bar */}
        <meta name="google" content="notranslate" />
      </head>

      <body className="font-sans antialiased">
        {/* Navbar renders the <GoogleTranslate /> dropdown */}
        {children}
      </body>
    </html>
  );
}