/* frontend/src/app/layout.tsx */
import type { Metadata } from 'next';
import { Roboto_Flex } from 'next/font/google';
import './globals.css';
import Script from 'next/script';

const roboto = Roboto_Flex({
  subsets: ['latin'],
  weight: ['100', '400', '700'],
  variable: '--font-roboto',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
  icons: { icon: '/favicon.ico' },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={roboto.variable}>
      <head>
        {/* This meta tag alone suppresses Chrome’s auto-translate bar */}
        <meta name="google" content="notranslate" />
      </head>

      {/* <body className="font-sans antialiased"> */}
        {/* Navbar renders the <GoogleTranslate /> dropdown */}
        {/* {children}
      </body> */}


          <body className="font-sans antialiased">
  {/* Chatbase script */}
  <Script id="chatbase-bubble" strategy="afterInteractive">
    {`
      window.chatbaseConfig = {
        chatbotId: "2KDhX_QMcGLg7-KbhH2qq",
      };

      (function() {
        var script = document.createElement("script");
        script.src = "https://www.chatbase.co/embed.min.js";
        script.async = true;
        document.body.appendChild(script);
      })();
    `}
  </Script>

  {/* Your page content */}
  {children}
</body>


    </html>
  );
}